[colors]
background = "#222436"
foreground = "#c8d3f5"

cursor_bg = "#c8d3f5"
cursor_fg = "#222436"
cursor_border = "#c8d3f5"

selection_bg = "#3654a7"
selection_fg = "#c8d3f5"

scrollbar_thumb = "#444a73"

ansi = ["#1b1d2b", "#ff757f", "#c3e88d", "#ffc777", "#82aaff", "#c099ff", "#86e1fc", "#828bb8"]
brights = ["#444a73", "#ff757f", "#c3e88d", "#ffc777", "#82aaff", "#c099ff", "#86e1fc", "#c8d3f5"]
